version: '3.2'
services:
  db:
    container_name: dev-utilities-db
    image: postgres:15
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    container_name: dev-utilities-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'pappu687'
    depends_on:
      - db
  nginx:
    container_name: dev-utilities-nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - api-2
  api:
    container_name: dev-utilities-api
    restart: on-failure
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    ports:
      - 5000:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
  api-2:
    container_name: dev-utilities-api-2
    restart: on-failure
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    command: npm run start:dev
    ports:
      - 5001:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
