#!/usr/bin/env sh

echo '🎨 Formatting...'
pnpm exec biome format --write ./src ||
(
  echo '❌ Formatting failed'
  false;
)

echo '🔎 Checking code...'
pnpm exec biome check --write ./src ||
(
  echo '❌ Code checking failed'
  false;
)

git add $(git diff --cached --name-only --diff-filter=ACM)

echo '✅ Linting and Formatting passed'

exit 0
